### ISSUE TITLE
Smile is not as expected

### ISSUE THREAD

**Issue by steininge** [kebu/py-avataaars#2]
Hi, 

thanks for a great package!

The MouthType.SMILE produces a smile with no teeth and tongue, whereas the expected smile (ref getavataaars.com) is with teeth and tongue. Is py-avataaars using an older version of the avatar components? If so, it would be great if this could be updated..

Cheers,
Stein

**Comment by kebu** [comment]
Hi, 
thanks for letting me know about this issue, I will check that. 
TBH if didn't update, maybe that's the reason.

Cheers
Krzysiek

**Comment by kebu** [comment]
Fixed, same issue was in several mouth types.

**Comment by steininge** [comment]
Hi Krzysztof,

thanks for looking into this so quickly!

I upgraded to version 1.0.0, but now I get the error below. It seems like
the smile template may be missing, and I get the same for grimace. I
upgraded jinja2 to version 2.11.2, but that didn't work.
I also tried to uninstall and reinstall. Am I doing something wrong, or is
there an issue in the new deployment?

TemplateNotFound: face/mouth\smile.svg at
C:/pyenv/rpa3.7.2/lib/site-packages/jinja2/loaders.py,
line 31 called from C:/pyenv/rpa3.7.2/lib/site-packages/jinja2/loaders.py,
line 232 called from
C:/pyenv/rpa3.7.2/lib/site-packages/py_avataaars/templates/face.svg,
line 3 called from
C:/pyenv/rpa3.7.2/lib/site-packages/py_avataaars/templates/main.svg,
line 81 called from
C:/pyenv/rpa3.7.2/lib/site-packages/py_avataaars/templates/base.svg,
line 3 called from
C:/pyenv/rpa3.7.2/lib/site-packages/py_avataaars/templates/main.svg,
line 8 called from C:/pyenv/rpa3.7.2/lib/site-packages/jinja2/_compat.py,
line 37 called from C:/pyenv/rpa3.7.2/lib/site-packages/jinja2/environment.py,
line 780 called from C:/pyenv/rpa3.7.2/lib/site-packages/jinja2/environment.py,
line 1008 called from
C:/pyenv/rpa3.7.2/lib/site-packages/jinja2/asyncsupport.py,
line 76 called from
C:/pyenv/rpa3.7.2/lib/site-packages/py_avataaars/__init__.py,
line 285 called from
C:/pyenv/rpa3.7.2/lib/site-packages/py_avataaars/__init__.py,
line 290

**Comment by kebu** [comment]
@steininge Should work with 1.0.1 version

**Comment by steininge** [comment]
Hi, it works well on Linux, but I still get the same error on windows. The local template path is changed, but it fails when building the full path in jinja2. 

TemplateNotFound: face\mouth\smile.svg
at C:/pyenv/rpa3.7.2/lib/site-packages/jinja2/loaders.py, line 32
  called from C:/pyenv/rpa3.7.2/lib/site-packages/jinja2/loaders.py, line 245
  called from C:/pyenv/rpa3.7.2/lib/site-packages/py_avataaars/templates/face.svg, line 3

**Comment by steininge** [comment]
Great, with 1.0.2 it runs perfectly on Windows too. Thanks!
